// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package db

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type Userrole string

const (
	UserroleGuest Userrole = "guest"
	UserroleUser  Userrole = "user"
	UserroleAdmin Userrole = "admin"
)

func (e *Userrole) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = Userrole(s)
	case string:
		*e = Userrole(s)
	default:
		return fmt.Errorf("unsupported scan type for Userrole: %T", src)
	}
	return nil
}

type NullUserrole struct {
	Userrole Userrole `json:"userrole"`
	Valid    bool     `json:"valid"` // Valid is true if Userrole is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullUserrole) Scan(value interface{}) error {
	if value == nil {
		ns.Userrole, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.Userrole.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullUserrole) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.Userrole), nil
}

type Account struct {
	ID        string           `json:"id"`
	Role      Userrole         `json:"role"`
	Username  string           `json:"username"`
	Password  string           `json:"password"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
}

type Form struct {
	ID         string           `json:"id"`
	ViewerName string           `json:"viewer_name"`
	Email      string           `json:"email"`
	Phone      string           `json:"phone"`
	CreatedAt  pgtype.Timestamp `json:"created_at"`
}

type Post struct {
	ID        int32            `json:"id"`
	ViewerID  int64            `json:"viewer_id"`
	Title     string           `json:"title"`
	Article   string           `json:"article"`
	Pictures  interface{}      `json:"pictures"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
}

type Session struct {
	ID        int32            `json:"id"`
	Token     string           `json:"token"`
	Role      string           `json:"role"`
	Issuer    string           `json:"issuer"`
	Subject   string           `json:"subject"`
	Exp       pgtype.Timestamp `json:"exp"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
}

type Viewer struct {
	ID     int64            `json:"id"`
	Ip     pgtype.Text      `json:"ip"`
	ViewAt pgtype.Timestamp `json:"view_at"`
}
