CREATE TABLE Viewer (
  id bigint PRIMARY KEY,
  ip varchar(15),
  view_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE Form (
  id VARCHAR(8) PRIMARY KEY,
  -- viewer_id bigint NOT NULL,
  viewer_name VARCHAR(255) NOT NULL,
  email VARCHAR(255) NOT NULL,
  phone VARCHAR(20) NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE Post (
  id INT PRIMARY KEY,
  viewer_id BIGINT NOT NULL,
  title VARCHAR(255) NOT NULL,
  article VARCHAR(255) NOT NULL,
  pictures LONGBLOB,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TYPE UserRole AS ENUM ('guest', 'user', 'admin');

CREATE TABLE Account (
  id VARCHAR(8) PRIMARY KEY,
  role UserRole NOT NULL,
  username VARCHAR(255) NOT NULL,
  password VARCHAR(255) NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE Session (
  id SERIAL PRIMARY KEY,
  token VARCHAR(255) NOT NULL,
  role VARCHAR(50) NOT NULL,
  issuer VARCHAR(255) NOT NULL,
  subject VARCHAR(255) NOT NULL,
  exp TIMESTAMP NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- ALTER TABLE Session ADD FOREIGN KEY (id) REFERENCES User(id);


-- ALTER TABLE Form ADD FOREIGN KEY (viewer_id) REFERENCES Viewer (id);

-- ALTER TABLE Post ADD FOREIGN KEY (viewer_id) REFERENCES Viewer (id);

