// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: community.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createCommunity = `-- name: createCommunity :one
INSERT INTO Community (
  id,
  community_name,
  photo,
  created_at
) VALUES (
  $1,$2,$3,CURRENT_TIMESTAMP
) RETURNING id, community_name, photo, created_at
`

type createCommunityParams struct {
	ID            uuid.UUID `json:"id"`
	CommunityName string    `json:"community_name"`
	Photo         []byte    `json:"photo"`
}

func (q *Queries) createCommunity(ctx context.Context, arg createCommunityParams) (Community, error) {
	row := q.db.QueryRow(ctx, createCommunity, arg.ID, arg.CommunityName, arg.Photo)
	var i Community
	err := row.Scan(
		&i.ID,
		&i.CommunityName,
		&i.Photo,
		&i.CreatedAt,
	)
	return i, err
}

const searchCommunityName = `-- name: searchCommunityName :many
SELECT id, community_name
FROM Community
WHERE community_name like $1
`

type searchCommunityNameRow struct {
	ID            uuid.UUID `json:"id"`
	CommunityName string    `json:"community_name"`
}

func (q *Queries) searchCommunityName(ctx context.Context, communityName string) ([]searchCommunityNameRow, error) {
	rows, err := q.db.Query(ctx, searchCommunityName, communityName)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []searchCommunityNameRow{}
	for rows.Next() {
		var i searchCommunityNameRow
		if err := rows.Scan(&i.ID, &i.CommunityName); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
