// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package db

import (
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Account struct {
	ID              uuid.UUID   `json:"id"`
	Role            string      `json:"role"`
	Username        string      `json:"username"`
	Password        string      `json:"password"`
	Photo           pgtype.Text `json:"photo"`
	IsEmailVerified bool        `json:"is_email_verified"`
	CreatedAt       time.Time   `json:"created_at"`
}

type Comment struct {
	ID        uuid.UUID `json:"id"`
	PostID    uuid.UUID `json:"post_id"`
	UserID    uuid.UUID `json:"user_id"`
	Text      string    `json:"text"`
	Upvotes   int32     `json:"upvotes"`
	CreatedAt time.Time `json:"created_at"`
}

type Community struct {
	ID            uuid.UUID `json:"id"`
	CommunityName string    `json:"community_name"`
	Photo         []byte    `json:"photo"`
	CreatedAt     time.Time `json:"created_at"`
}

type Form struct {
	ID         uuid.UUID `json:"id"`
	ViewerName string    `json:"viewer_name"`
	Email      string    `json:"email"`
	Phone      string    `json:"phone"`
	CreatedAt  time.Time `json:"created_at"`
}

type Post struct {
	ID          uuid.UUID `json:"id"`
	Title       string    `json:"title"`
	Article     string    `json:"article"`
	Picture     []byte    `json:"picture"`
	UserID      uuid.UUID `json:"user_id"`
	CommunityID uuid.UUID `json:"community_id"`
	Upvotes     int32     `json:"upvotes"`
	CreatedAt   time.Time `json:"created_at"`
}

type Reply struct {
	ID        uuid.UUID `json:"id"`
	CommentID uuid.UUID `json:"comment_id"`
	UserID    uuid.UUID `json:"user_id"`
	Text      string    `json:"text"`
	Upvotes   int32     `json:"upvotes"`
	CreatedAt time.Time `json:"created_at"`
}

type Session struct {
	ID        uuid.UUID          `json:"id"`
	Username  string             `json:"username"`
	Role      string             `json:"role"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type VerifyEmail struct {
	Username   string    `json:"username"`
	SecretCode string    `json:"secret_code"`
	IsUsed     bool      `json:"is_used"`
	ExpiresAt  time.Time `json:"expires_at"`
	CreatedAt  time.Time `json:"created_at"`
}
