// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateVerifyEmail(ctx context.Context, arg CreateVerifyEmailParams) (VerifyEmail, error)
	UpdateAccount(ctx context.Context, arg UpdateAccountParams) (Account, error)
	UpdateVerifyEmail(ctx context.Context, arg UpdateVerifyEmailParams) (VerifyEmail, error)
	authPassword(ctx context.Context, username string) (string, error)
	authUsername(ctx context.Context, username string) (string, error)
	createAccount(ctx context.Context, arg createAccountParams) (Account, error)
	createPost(ctx context.Context, arg createPostParams) (Post, error)
	createSession(ctx context.Context, arg createSessionParams) (Session, error)
	deleteSession(ctx context.Context, username string) error
	getAccountIDbyID(ctx context.Context, id uuid.UUID) (uuid.UUID, error)
	getAccountIDbyUsername(ctx context.Context, username string) (uuid.UUID, error)
	getAccountRolebyUsername(ctx context.Context, username string) (Userrole, error)
	getAllPost(ctx context.Context) ([]Post, error)
	getAllSessionID(ctx context.Context) ([]uuid.UUID, error)
	getFormsID(ctx context.Context, id uuid.UUID) (uuid.UUID, error)
	getSessionIDbyID(ctx context.Context, id uuid.UUID) (uuid.UUID, error)
	loginAccount(ctx context.Context, arg loginAccountParams) (Account, error)
	submitForm(ctx context.Context, arg submitFormParams) (Form, error)
}

var _ Querier = (*Queries)(nil)
