// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Account struct {
	ID        int32            `json:"id"`
	Role      interface{}      `json:"role"`
	Username  string           `json:"username"`
	Password  string           `json:"password"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
}

type Form struct {
	ID         int32            `json:"id"`
	ViewerName string           `json:"viewer_name"`
	Email      string           `json:"email"`
	Phone      string           `json:"phone"`
	CreatedAt  pgtype.Timestamp `json:"created_at"`
}

type Post struct {
	ID        int32            `json:"id"`
	ViewerID  int64            `json:"viewer_id"`
	Title     string           `json:"title"`
	Article   string           `json:"article"`
	Pictures  interface{}      `json:"pictures"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
}

type Session struct {
	ID        int32            `json:"id"`
	Token     string           `json:"token"`
	Role      string           `json:"role"`
	Issuer    string           `json:"issuer"`
	Subject   string           `json:"subject"`
	Exp       pgtype.Timestamp `json:"exp"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
}

type Viewer struct {
	ID     int64            `json:"id"`
	Ip     pgtype.Text      `json:"ip"`
	ViewAt pgtype.Timestamp `json:"view_at"`
}
