// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package db

import (
	"context"
)

type Querier interface {
	authPassword(ctx context.Context, username string) (string, error)
	authUsername(ctx context.Context, username string) (string, error)
	createAccount(ctx context.Context, arg createAccountParams) (Account, error)
	createSession(ctx context.Context, arg createSessionParams) ([]Session, error)
	// -- name: getFormByID :one
	// SELECT *
	// FROM form
	// WHERE id = $1;
	getFormsID(ctx context.Context, id int32) ([]int32, error)
	loginAccount(ctx context.Context, arg loginAccountParams) (Account, error)
	removeSession(ctx context.Context, token string) error
	submitForm(ctx context.Context, arg submitFormParams) (Form, error)
}

var _ Querier = (*Queries)(nil)
