// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: form.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const getFormsID = `-- name: getFormsID :one
SELECT id
FROM Form
WHERE id = $1
LIMIT 1
`

func (q *Queries) getFormsID(ctx context.Context, id uuid.UUID) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, getFormsID, id)
	err := row.Scan(&id)
	return id, err
}

const submitForm = `-- name: submitForm :one
INSERT INTO Form(
  id,
  viewer_name,
  email,
  phone,
  created_at
) VALUES (
  $1,$2,$3,$4,CURRENT_TIMESTAMP
) RETURNING id, viewer_name, email, phone, created_at
`

type submitFormParams struct {
	ID         uuid.UUID `json:"id"`
	ViewerName string    `json:"viewer_name"`
	Email      string    `json:"email"`
	Phone      string    `json:"phone"`
}

func (q *Queries) submitForm(ctx context.Context, arg submitFormParams) (Form, error) {
	row := q.db.QueryRow(ctx, submitForm,
		arg.ID,
		arg.ViewerName,
		arg.Email,
		arg.Phone,
	)
	var i Form
	err := row.Scan(
		&i.ID,
		&i.ViewerName,
		&i.Email,
		&i.Phone,
		&i.CreatedAt,
	)
	return i, err
}
